volumes:
 wordpress_db_data:
  driver_opts:
   o: bind
   type: none
   device: /home/etomiyos/data/mariadb
 wordpress_files:
  driver_opts:
   o: bind
   type: none
   device: /home/etomiyos/data/wordpress

networks:
 network:
  driver: bridge

services:
 mariadb:
  build:
   context: ./requirements/mariadb/
  container_name: mariadb
  restart: on-failure
  env_file:
   - .env
  networks:
   - network
  volumes:
  - wordpress_db_data:/var/lib/mysql


 nginx:
  build:
   context: ./requirements/nginx/
  container_name: nginx
  restart: on-failure
  ports:
   - 443:443
  volumes:
   - wordpress_files:/var/custom_www/
  networks:
   - network
  depends_on:
    wordpress:
      condition: service_healthy

  

 wordpress:
  build:
   context: ./requirements/wordpress/
  env_file:
   - .env
  container_name: wordpress
  restart: on-failure
  volumes:
   - wordpress_files:/var/custom_www/
  networks:
   - network
  depends_on:
    mariadb: 
      condition: service_healthy